const invoice = {
  id: '5df3180a09ea16dc4b95f910',
  invoice_no: '201906-28',
  balance: '$2,283.74',
  company: 'MANTRIX',
  email: 'susanafuentes@mantrix.com',
  phone: '+1 (872) 588-3809',
  address: '922 Campus Road, Drytown, Wisconsin, 1986',
  trans_date: '2019-09-12',
  due_date: '2019-10-12',
  items: [
    {
      sno: 1,
      desc: 'ad sunt culpa occaecat qui',
      qty: 5,
      rate: 405.89,
    },
    {
      sno: 2,
      desc: 'cillum quis sunt qui aute',
      qty: 5,
      rate: 373.11,
    },
    {
      sno: 3,
      desc: 'ea commodo labore culpa irure',
      qty: 5,
      rate: 458.61,
    },
    {
      sno: 4,
      desc: 'nisi consequat et adipisicing dolor',
      qty: 10,
      rate: 725.24,
    },
    {
      sno: 5,
      desc: 'proident cillum anim elit esse',
      qty: 4,
      rate: 141.02,
    },
    {
      sno: 6,
      desc: 'proident cillum anim elit esse',
      qty: 4,
      rate: 141.02,
    },
    {
      sno: 7,
      desc: 'proident cillum anim elit esse',
      qty: 4,
      rate: 141.02,
    },
    {
      sno: 8,
      desc: 'proident cillum anim elit esse',
      qty: 4,
      rate: 141.02,
    },
    {
      sno: 9,
      desc: 'proident cillum anim elit esse',
      qty: 4,
      rate: 141.02,
    },
    {
      sno: 10,
      desc: 'proident cillum anim elit esse',
      qty: 4,
      rate: 141.02,
    },
    {
      sno: 11,
      desc: 'proident cillum anim elit esse',
      qty: 4,
      rate: 141.02,
    },
    {
      sno: 12,
      desc: 'proident cillum anim elit esse',
      qty: 4,
      rate: 141.02,
    },
    {
      sno: 13,
      desc: 'proident cillum anim elit esse',
      qty: 4,
      rate: 141.02,
    },
    {
      sno: 14,
      desc: 'proident cillum anim elit esse',
      qty: 4,
      rate: 141.02,
    },
    {
      sno: 15,
      desc: 'proident cillum anim elit esse',
      qty: 4,
      rate: 141.02,
    },
    {
      sno: 16,
      desc: 'proident cillum anim elit esse',
      qty: 4,
      rate: 141.02,
    },
    {
      sno: 17,
      desc: 'proident cillum anim elit esse',
      qty: 4,
      rate: 141.02,
    },
    {
      sno: 18,
      desc: 'ad sunt culpa occaecat qui',
      qty: 5,
      rate: 405.89,
    },
    {
      sno: 19,
      desc: 'cillum quis sunt qui aute',
      qty: 5,
      rate: 373.11,
    },
    {
      sno: 20,
      desc: 'ea commodo labore culpa irure',
      qty: 5,
      rate: 458.61,
    },
    {
      sno: 21,
      desc: 'nisi consequat et adipisicing dolor',
      qty: 10,
      rate: 725.24,
    },
    {
      sno: 22,
      desc: 'proident cillum anim elit esse',
      qty: 4,
      rate: 141.02,
    },
    {
      sno: 23,
      desc: 'proident cillum anim elit esse',
      qty: 4,
      rate: 141.02,
    },
    {
      sno: 24,
      desc: 'proident cillum anim elit esse',
      qty: 4,
      rate: 141.02,
    },
    {
      sno: 25,
      desc: 'proident cillum anim elit esse',
      qty: 4,
      rate: 141.02,
    },
    {
      sno: 26,
      desc: 'proident cillum anim elit esse',
      qty: 4,
      rate: 141.02,
    },
    {
      sno: 27,
      desc: 'proident cillum anim elit esse',
      qty: 4,
      rate: 141.02,
    },
    {
      sno: 28,
      desc: 'proident cillum anim elit esse',
      qty: 4,
      rate: 141.02,
    },
    {
      sno: 29,
      desc: 'proident cillum anim elit esse',
      qty: 4,
      rate: 141.02,
    },
    {
      sno: 30,
      desc: 'proident cillum anim elit esse',
      qty: 4,
      rate: 141.02,
    },
    {
      sno: 31,
      desc: 'proident cillum anim elit esse',
      qty: 4,
      rate: 141.02,
    },
    {
      sno: 32,
      desc: 'proident cillum anim elit esse',
      qty: 4,
      rate: 141.02,
    },
    {
      sno: 33,
      desc: 'proident cillum anim elit esse',
      qty: 4,
      rate: 141.02,
    },
    {
      sno: 34,
      desc: 'proident cillum anim elit esse',
      qty: 4,
      rate: 141.02,
    },
    {
      sno: 35,
      desc: 'proident cillum anim elit esse',
      qty: 4,
      rate: 141.02,
    },
    {
      sno: 36,
      desc: 'proident cillum anim elit esse',
      qty: 4,
      rate: 141.02,
    },
    {
      sno: 37,
      desc: 'proident cillum anim elit esse',
      qty: 4,
      rate: 141.02,
    },
    {
      sno: 38,
      desc: 'proident cillum anim elit esse',
      qty: 4,
      rate: 141.02,
    },
    {
      sno: 39,
      desc: 'proident cillum anim elit esse',
      qty: 4,
      rate: 141.02,
    },
    {
      sno: 40,
      desc: 'proident cillum anim elit esse',
      qty: 4,
      rate: 141.02,
    },
    {
      sno: 41,
      desc: 'proident cillum anim elit esse',
      qty: 4,
      rate: 141.02,
    },
    {
      sno: 42,
      desc: 'proident cillum anim elit esse',
      qty: 4,
      rate: 141.02,
    },
    {
      sno: 43,
      desc: 'proident cillum anim elit esse',
      qty: 4,
      rate: 141.02,
    },
    {
      sno: 44,
      desc: 'proident cillum anim elit esse',
      qty: 4,
      rate: 141.02,
    },
    {
      sno: 45,
      desc: 'proident cillum anim elit esse',
      qty: 4,
      rate: 141.02,
    },
    {
      sno: 46,
      desc: 'proident cillum anim elit esse',
      qty: 4,
      rate: 141.02,
    },
    {
      sno: 47,
      desc: 'proident cillum anim elit esse',
      qty: 4,
      rate: 141.02,
    },
    {
      sno: 48,
      desc: 'proident cillum anim elit esse',
      qty: 4,
      rate: 141.02,
    },
    {
      sno: 49,
      desc: 'proident cillum anim elit esse',
      qty: 4,
      rate: 141.02,
    },
    {
      sno: 50,
      desc: 'proident cillum anim elit esse',
      qty: 4,
      rate: 141.02,
    },
  ],
}

export default invoice
